#список точек финишов на аренах
finishes:
  - arena1finish
  - arena2finish
  - arena3finish


#используется когда игрок захлдит в сеть или покидает заезд не командой
#чтобы если что, убрать его с арены
#регины арены должно включать в себя ПОЛНОСТЬЮ ВСЮ АРЕНУ, все ее части
arenas-regions:
  - arena1
  - arena2
  - arena3

sounds:
  volume: 100
  joined: ""
  timer-to-game-tick: ""
  finished: ""
  stopped: ""

jump-item:
  top: 0.1 #Модификатор ускорения вверх. Ускорение в перед фиксированное в поле if-top-forward-velocity
  enabled: true
  cooldown: 5
  material: DIRT
  name: Стрибок
  lore:
    - "Опис строка 1"

#максимальное колчество победителей
max-winners: 4

#передние ускорение, которое дается при подпригивании
if-top-forward-velocity: 2.0

times:
  player-wait: 20 #время ожидания игроков на арене
  max-game-duration: 60 #время длительности самого заеда
  game-prepare: 5 #время подготовки к заезду, блокировки движения

after-game-spawn:
  world: world
  position:
    x: -9
    y: -60
    z: -20

#блоки, которые дают ускорение вверх
to-top-blocks:
  LADDER: 0.1
  DIRT: 0.2

#блоки, которые дают ускорение вперед
to-forward-blocks:
  DIRT: 0.2