times:
  player-wait: 20
  max-game-duration: 60
  game-prepare: 5


after-game-spawn:
  world: world
  position:
    x: 0
    y: 0
    z: 0

to-top-blocks:
  LADDER: 0.1
  DIRT: 0.2

to-forward-blocks:
  DIRT: 0.2