times:
  player-wait: 20
  max-game-duration: 60
  game-prepare: 5

after-game-spawn:
  world: world
  position:
    x: -9
    y: -60
    z: -20

to-top-blocks:
  LADDER: 0.1
  DIRT: 0.2

to-forward-blocks:
  DIRT: 0.2